# Generated by Django 4.1.3 on 2022-12-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBook', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('yearCreate', models.DateField()),
                ('public', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('img_base64', models.CharField(blank=True, max_length=200000)),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lesson_12_Models_writers.categorie')),
            ],
        ),
    ]
