# Generated by Django 4.1.3 on 2022-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBook', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('yearCreate', models.DateField()),
                ('public', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('img_base64', models.CharField(blank=True, max_length=200000)),
                ('style', models.CharField(choices=[('Фэнтези', 'Фэнтези'), ('Детективы', 'Детективы')], max_length=100)),
            ],
        ),
    ]
