# Generated by Django 4.1.3 on 2022-12-16 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('financing', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinLengthValidator(0)])),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinLengthValidator(0)])),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('departmentId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.department')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProfessor', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(0.01)])),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lectureRoom', models.CharField(max_length=100)),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.subject')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.group')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.students')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.group')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='GroupsCurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.curator')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.group')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='facultyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson_11_Models.facultie'),
        ),
    ]
