# Generated by Django 4.1.3 on 2022-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hockeyteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchNumber', models.IntegerField()),
                ('roundNumber', models.IntegerField()),
                ('dateUtc', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('homeTeam', models.CharField(max_length=100)),
                ('awayTeam', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100, null=True)),
                ('homeTeamScore', models.IntegerField(null=True)),
                ('awayTeamScore', models.IntegerField(null=True)),
            ],
        ),
    ]
